version: '3.8'
services:
  app:
    image: ${DOCKER_REGISTRY:-docker.io}/nileshk12/yii2-app:${TAG:-latest}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - yii2-network
networks:
  yii2-network:
    driver: overlay
    attachable: true
